# Site Settings
name: Minflix
title: Minflix | Minsu's TechBlog
description: Minsu's techblog, thanks to developer Thiago Rossener.
google_adsense_account: ca-pub-8136917168968629
google_adsense_ad_slot: "6051878381"
google_adsense_side_ad_slot: "6051878381"
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
category_navigation:
  - title: C언어
    slug: C
    url: /category/c/
    description: 기초 문법부터 포인터, 구조체까지
  - title: 자료구조
    slug: 자료구조
    url: /category/data-structures/
    description: 배열, 리스트, 트리, 그래프, 해시
  - title: 객체지향프로그래밍
    slug: 객체지향프로그래밍
    url: /category/oop/
    description: C++와 OOP 개념 정리
  - title: NLP/AI
    slug: NLP, AI
    url: /category/nlp-ai/
    description: 언어모델과 고전 신경망 논문
  - title: 유학 준비
    url: /category/study-abroad/
    categories:
      - blog, 어학
      - blog, 어학, 장학금, 논문, 운전면허
    description: TOEFL, GRE, 장학금, 준비 기록
  - title: 회고/Blog
    slug: blog
    url: /category/blog/
    description: 회고와 개인 기록

email: jungsi199@naver.com
# See: https://disqus.com/
disqus_username: minflex
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id


# Social Media Settings
# Remove the item if you don't need it
github_username: Minsuchoi-1999
instagram_username: minsu.c.0621
linkedin_username: minsu-choi-256aa7304


# Posts Settings
show_time_bar: true
show_modal_on_exit: true
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minsuchoi-1999.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "ko-KR"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-sitemap
# Exclude my node related stuff
exclude:
  [
    ".sass-cache/",
    "docs/",
    "vendor/",
    "LICENSE",
    "CHANGELOG.md",
    "jekflix.gemspec",
    "package.json",
    "package-lock.json",
    "src",
    "node_modules",
    "initpost.sh",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "README.md",
  ]

# Theme
version: v3.1.2

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  math_engine_opts:
    preview: true
