name: Minflix
title: Minflix | Minsu's TechBlog
description: Minsu's techblog, thanks to developer Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml

email: jungsi199@naver.com
# See: https://disqus.com/
disqus_username: minflex
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
